name: Publish Website
on:
  push:
    branches:
      - master
    paths:
      - 'content/**'
jobs:
  Publish-Website:
    runs-on: python:3.8.16-slim
    env:
      LANG: en_US.UTF-8
      LC_ALL: en_US.UTF-8
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v3
        with:
          path: "requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
      - name: Install base dependencies
        run: |
          apt install -y curl
          curl https://files.stork-search.net/releases/v1.5.0/stork-ubuntu-20-04 -o stork
          chmod +x stork
          mv ./stork /usr/bin/stork
          curl -sL https://deb.nodesource.com/setup_14.x | bash -
          apt-get install -y nodejs
          npm install -g sass
          npm install -g juice
          publishing/*.sh ./
          chmod 777 *.sh
      - name: Run pelican
        run: |
          pelican --delete-output-directory content
          mkdir final_out
          rsync -razvP --delete --exclude /CNAME --exclude /.git output/ final_out/
      - name: Merge with public site
        uses: cpina/github-action-push-to-another-repository@v1.5.1
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'final_out'
          destination-github-username: 'andrewpollack'
          destination-repository-name: 'this-week-in-rust.github.io'
          user-email: andrewpkq@gmail.com
          target-branch: master
